include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_specify_types: true
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_empty_else: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_field_initializers_in_const_classes: true
    avoid_init_to_null: true
    avoid_multiple_declarations_per_line: true
    avoid_print: true
    avoid_return_types_on_setters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    camel_case_types: true
    cascade_invocations: true
    collection_methods_unrelated_type: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    depend_on_referenced_packages: true
    directives_ordering: true
    discarded_futures: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    eol_at_end_of_file: true
    exhaustive_cases: true
    file_names: true
    flutter_style_todos: true
    leading_newlines_in_multiline_strings: true
    lines_longer_than_80_chars: true
    literal_only_boolean_expressions: true
    parameter_assignments: true
    prefer_conditional_assignment: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_is_not_operator: true
    unnecessary_new: true
    unnecessary_parenthesis: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    use_enums: true
    use_is_even_rather_than_modulo: true
    prefer_const_constructors: true
    omit_local_variable_types: false
    prefer_final_fields: true
    use_key_in_widget_constructors: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true



