name: Check for Comments

on:
  pull_request:
    paths:
      - '**/*.dart'
    branches:
      - master
      
jobs:
  check-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for comments in the code
        run: |
          if grep -r -I "//" .; then
            echo "Comments found in the code. Please remove them before submitting the PR."
            exit 1
          fi
          if grep -r -I "/*" .; then
            echo "Comments found in the code. Please remove them before submitting the PR."
            exit 1
          fi
        shell: bash
